services:
  api:
    image: apple-health-influx-api:latest
    container_name: apple_health_influx
    ports:
      - "5055:5055"
    restart: unless-stopped
    env_file: .env
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:2
    container_name: influxdb
    ports:
      - "8086:8086"
    restart: unless-stopped
    volumes:
      - influxdb-data:/var/lib/influxdb2

volumes:
  influxdb-data: